### ISSUE TITLE
移植到微信小游戏，效率低了很多

### ISSUE THREAD

**Issue by msyzzm** [sanyuered/WeChat-MiniProgram-WebAR#2]
我把代码移植到了微信小游戏，使用图片识别。同样的图片，同样的算法，同一部手机，比对时间长了很多。小程序里大概200ms，小游戏要1000-4000ms，时间变化幅度很大。请问有什么解决思路么？

**Comment by pxim** [comment]
我在ios 小程序上，基本很难识别，你们也是这样么

**Comment by sanyuered** [comment]
> 我在ios 小程序上，基本很难识别，你们也是这样么

1、iOS和Android微信都可以检测到识别图，但是在Android检测速度300毫秒内，在iOS检测速度2000毫秒以上。
2、图像检测AR没法在微信中提高运行速度， 但人脸检测AR可以使用另一个项目。 https://github.com/sanyuered/WeChat-MiniProgram-AR-TFJS
3、另一个人脸检测AR项目使用了深度学习技术，在iOS上的检测速度在80毫秒内。

**Comment by pxim** [comment]
> AR



> > 我在ios 小程序上，基本很难识别，你们也是这样么
> 
> 1、iOS和Android微信都可以检测到识别图，但是在Android检测速度300毫秒内，在iOS检测速度2000毫秒以上。
> 2、图像检测AR没法在微信中提高运行速度， 但人脸检测AR可以使用另一个项目。 https://github.com/sanyuered/WeChat-MiniProgram-AR-TFJS
> 3、另一个人脸检测AR项目使用了深度学习技术，在iOS上的检测速度在80毫秒内。

了解了，非常感谢，

**Comment by sanyuered** [comment]
> 我在ios 小程序上，基本很难识别，你们也是这样么

我将小程序相同的代码改为网页版，iOS版微信小程序识别一次耗时4000ms，而在iOS Safari上只耗时60ms。网页版：https://github.com/sanyuered/WebAR
