### ISSUE TITLE
怎么识别多张标识图呢

### ISSUE THREAD

**Issue by upwardlwy** [sanyuered/WeChat-MiniProgram-WebAR#3]
我们需要实现多张图做为标识图，每张标识图识别成功则加载一个对应的3D模型，问题是，
var tracker = new ImageTracker(patternImageArray); 
tracker.on('track', function (event) { ... }) 
只能同一时间监听一张标识图，有什么办法把多张标识图提前内置进去吗？

**Comment by sanyuered** [comment]
1、先使用imageBusiness.js的initTracker方法增加多个标识图，然后使用ImageTracker.js的ImageTracker.prototype.track方法循环地检测。
2、图像检测和识别算法在小程序的运行速度很慢，建议使用服务端开发您的这个需求。
