### ISSUE TITLE
请问可以加一个实时监测，自动识别图片的例子么？

### ISSUE THREAD

**Issue by pxim** [sanyuered/WeChat-MiniProgram-WebAR#4]
现在必须拍一下照片，才监测一下；可以 点击一个按钮，然后就自动监测，大概300毫秒轮询监测这种，不手动拍照么？

**Comment by sanyuered** [comment]
在Image AR一栏增加了“Access a camera“的入口，是实时的视频模式。检测一帧图像在Android上的速度约300毫秒，在iOS上的速度约2000毫秒以上。

**Comment by pxim** [comment]
> 检测

谢谢

请问下，ar.js里用的识别 标识，自然图片 的那种识别库能在小程序里用么；我体验过 在ios safari上，效率挺好的；

**Comment by pxim** [comment]
> 在Image AR一栏增加了“Access a camera“的入口，是实时的视频模式。检测一帧图像在Android上的速度约300毫秒，在iOS上的速度约2000毫秒以上。

谢谢

请问下，ar.js里用的识别 标识，自然图片 的那种识别库能在小程序里用么；我体验过 在ios safari上，效率挺好的；
https://github.com/AR-js-org/AR.js

**Comment by sanyuered** [comment]
1、我测试了AR.js的自然图片的跟踪，恐龙模型在画面中抖动得很剧烈。2、微信小程序每个分包不能超过2MB大小，AR.js的文件体积超过了小程序的限制。3、网页版图像跟踪在浏览器中比较快，而在小程序中很慢。4、这个项目有个网页版https://github.com/sanyuered/WebAR 我在iOS Safari上测试，每次识别只要几十毫秒。
