### ISSUE TITLE
open cv js Error Module is not defind 

### ISSUE THREAD

**Issue by LazyYangi** [sanyuered/WeChat-MiniProgram-WebAR#5]
![image](https://user-images.githubusercontent.com/30524761/145747367-8bfdfbae-cd70-4df6-8f24-6d5e0b98f3dd.png)
![1101639365688_ pic](https://user-images.githubusercontent.com/30524761/145747374-94156ec9-e2f4-4ae5-b13a-aeebfd7390fa.jpg)
ios 15.1 iphone 13

**Comment by sanyuered** [comment]
![4](https://user-images.githubusercontent.com/21356275/147376876-b27ac39b-ae39-44d3-a378-d1c9b2209a9f.jpg)
微信开发者工具--本地设置--取消选择“将JS编译成ES5“。原因是opencv_exec.js使用了es5不支持的语法。
