### ISSUE TITLE
invalid file: package_color_tracker/utils/imageBusiness.js, undefined:110

### ISSUE THREAD

**Issue by daniel87821** [sanyuered/WeChat-MiniProgram-WebAR#6]
message：Error: 非法的文件，错误信息：invalid file: package_color_tracker/utils/imageBusiness.js, undefined:110: SyntaxError: Unexpected token export,export {^^^^^^SyntaxError: Unexpected token export [20211222 17:28:18][wx49689a912dcd6e2e]
appid: wx49689a912dcd6e2e
openid: o6zAJs4IvPnXZUFfWQBnSB6QK_3U
ideVersion: 1.05.2111300
osType: win32-x64
time: 2021-12-22 17:28:20

**Comment by sanyuered** [comment]
这个问题是module.exports和export两种不同语法造成的。文件/package_color_tracker/utils/imageBusiness.js已更新。
