### ISSUE TITLE
关于ios 手机测试小程序

### ISSUE THREAD

**Issue by daniel87821** [sanyuered/WeChat-MiniProgram-WebAR#7]
您好，我使用苹果手机的微信小程序，测试图像跟踪（package_image_tracker）不成功。但安卓是成功的，请问有没有苹果手机跟踪自定义图像的demo？谢谢

**Comment by sanyuered** [comment]
1、iOS运行图像跟踪不成功的原因：小程序使用了UI界面上隐藏的画布组件获取图像数据。开始能工作，在2021年开始不能工作了。
2、package_image_tracker代码已经更新，使用了离屏画布组件代替隐藏画布组件，在iOS微信8.0.26版能正常运行，推测之前版本微信也能正常运行。
3、\package_image_tracker\pages\photo在iOS运行时间2100毫秒/帧，在Android运行时间270毫秒/帧。在iOS上，慢的没法使用。
4、\package_image_tracker\pages\camera使用了Experimental Worker，如果iOS微信版本号8.0.24及以上，则运行速度80毫秒/帧，与图像跟踪算法在网页中的运行速度相近。如果是Android和iOS微信旧版本，代码做了兼容性处理，也能运行起来，但运行速度和第3点相同。
